### ISSUE TITLE
Update to 'development woes' article

### ISSUE THREAD

**Issue by copiousfreetime** [LukeMcGurdy/lukemcgurdy.github.io#1]
Hi Luke,

I have updated hitimes to work as expected on windows with ruby 2.2. You should not have a problem anymore.

enjoy,

-jeremy

**Comment by LukeMcGurdy** [comment]
Cheers Jeremy. Much appreciated.

**Comment by LukeMcGurdy** [comment]
For posterity - http://lukemcgurdy.com/jekyll-hitimes-windows-7/
